### ISSUE TITLE
New Login Page

### ISSUE THREAD

**Issue by lukes-code** [rajritu833/Types-of-HTML-pages#10]
Hello, can I submit a new login page?

**Comment by rajritu833** [comment]
ok Sure @lukes-code

**Comment by lukes-code** [comment]
Ok thanks @rajritu833 I have submitted a PR. Please can you merge and add hacktoberfest-accepted label to it

**Comment by Pensuveze** [comment]
@lukes-code I want to contribute to this project. please tell me what to do ...
